#!/bin/bash
# Initialise the bundled PostgreSQL cluster:
# - Run initdb as the postgres user
# - Configure listen_addresses to localhost only (never exposed)
# - Start a temporary instance, create the docmost role/database, then stop it
# Subsequent boots skip this script (PG_VERSION marker file present).

set -euo pipefail

: "${PG_VERSION:?PG_VERSION not set}"
: "${PG_DATA:?PG_DATA not set}"
: "${POSTGRES_USER:?POSTGRES_USER not set}"
: "${POSTGRES_DB:?POSTGRES_DB not set}"
: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}"

PG_BIN="/usr/lib/postgresql/${PG_VERSION}/bin"
log() { echo "[aio-init-postgres] $*"; }

mkdir -p "$PG_DATA"
chown -R postgres:postgres "$PG_DATA"
chmod 700 "$PG_DATA"

log "Running initdb"
gosu postgres "$PG_BIN/initdb" \
  --pgdata="$PG_DATA" \
  --auth-host=scram-sha-256 \
  --auth-local=peer \
  --encoding=UTF8 \
  --no-locale \
  --username=postgres >/dev/null

# Lock down networking: only localhost, no remote TCP at all.
cat >> "$PG_DATA/postgresql.conf" <<EOF

# Docmost AIO overrides
listen_addresses = '127.0.0.1'
unix_socket_directories = '/var/run/postgresql'
port = 5432
log_destination = 'stderr'
logging_collector = off
EOF

# Replace pg_hba: allow only local socket + 127.0.0.1.
cat > "$PG_DATA/pg_hba.conf" <<EOF
# Auto-generated by docmost AIO. Do not edit.
local   all             postgres                                peer
local   all             all                                     scram-sha-256
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256
EOF

chown postgres:postgres "$PG_DATA/postgresql.conf" "$PG_DATA/pg_hba.conf"

log "Starting temporary postgres for bootstrap"
gosu postgres "$PG_BIN/pg_ctl" -D "$PG_DATA" -l /tmp/pg-bootstrap.log -w -t 60 start

log "Creating role and database"
gosu postgres "$PG_BIN/psql" -v ON_ERROR_STOP=1 --username postgres <<SQL
CREATE ROLE "${POSTGRES_USER}" WITH LOGIN PASSWORD '${POSTGRES_PASSWORD}';
CREATE DATABASE "${POSTGRES_DB}" OWNER "${POSTGRES_USER}";
SQL

log "Stopping bootstrap postgres"
gosu postgres "$PG_BIN/pg_ctl" -D "$PG_DATA" -m fast -w stop

log "PostgreSQL bootstrap complete"
